<?php
/**
 * Title: Consulting - Default Hero Page
 * Slug: consulting/hero-page-default
 * Categories: blockstrap-hero-sections
 * Viewport Width: 1280
 */

 $img_url = esc_url( get_theme_file_uri( 'assets/images/demo/city-buildings.jpeg' ) ); /* <?php echo esc_url( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"rgba(0,0,0,0.58)","bg_image_fixed":true,"bg_image":"<?php echo esc_url( $img_url ); ?>","bg_image_id":6335,"bg_image_xy":{"x":0.58,"y":0.76},"pt":"7","pt_lg":"10","pb_lg":"5","pl_lg":"4","border":"0"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='rgba(0,0,0,0.58)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='true'  bg_image_use_featured='false'  bg_image='<?php echo esc_url( $img_url ); ?>'  bg_image_id='6335'  bg_image_xy='{x:0.58,y:0.76}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt='7'  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='10'  pr_lg=''  pb_lg='5'  pl_lg='4'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 pt-7 pt-lg-10 pb-5 ps-4 border-0 bg-custom-color container-fluid" style="background-color:rgba(0,0,0,0.58);background-image:url(<?php echo esc_url( $img_url ); ?>);background-blend-mode:overlay;background-size:cover;background-attachment:fixed;background-position:57.99999999999999% 76%"><!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","className":"block-1618467995"} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_lg":"8","mb_lg":"","className":"block-1618467995"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg='8'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined col-8 col"><!-- wp:blockstrap/blockstrap-widget-post-title {"text_color":"white","font_size":"display-3","font_weight":"font-weight-bold","mb_lg":"0"} -->
[bs_post_title html_tag='h1'  is_link='false'  stretched_link='false'  text_color='white'  text_color_custom=''  font_size='display-3'  font_size_custom=''  font_line_height=''  font_weight='font-weight-bold'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-post-title -->

<!-- wp:blockstrap/blockstrap-widget-breadcrumb {"text_color":"white","content":"\u003cnav aria-label=\u0022breadcrumb\u0022 \u003e\u003col class=\u0022breadcrumb  m-0 p-0 pt-1\u0022\u003e\u003cli class=\u0022breadcrumb-item text-white mb-0\u0022\u003e\u003ca href=\u0022http://consulting.local\u0022\u003eHome\u003c/a\u003e\u003c/li\u003e\u003cli class=\u0022breadcrumb-item text-white mb-0\u0022\u003e\u003ca href=\u0022#\u0022\u003eBackend\u003c/a\u003e\u003c/li\u003e\u003cli class=\u0022breadcrumb-item active text-white mb-0\u0022 aria-current=\u0022page\u0022\u003eBlock Editor\u003c/li\u003e\u003c/ol\u003e\u003c/nav\u003e"} -->
[bs_breadcrumb hide_home='false'  home_text=''  icon_class=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  text_color='white'  text_color_custom=''  font_size=''  font_size_custom=''  font_line_height=''  font_weight=''  font_case=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-breadcrumb --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->