<?php
/**
 * Title: Consulting - Showcases achievements and impact.
 * Slug: consulting/hero-cta
 * Categories: call-to-action
 * Viewport Width: 1280
 */

 $img_url = esc_url( get_theme_file_uri( 'assets/images/demo/city-buildings.jpeg' ) ); /* <?php echo esc_url( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"rgba(0,0,0,0.77)","bg_gradient":"linear-gradient(135deg,rgb(30,23,126) 4%,rgb(96,41,182) 100%)","bg_image":"<?php echo esc_url( $img_url ); ?>","bg_image_id":6335,"bg_image_xy":{"x":0.5,"y":0.62},"mb_lg":"","pt_md":"6","pb_md":"6","pt_lg":"8","pr_lg":"0","pl_lg":"0","position":"position-relative","display_lg":"d-lg-flex","flex_justify_content_lg":"justify-content-lg-center"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='rgba(0,0,0,0.77)'  bg_gradient='linear-gradient(135deg,rgb(30,23,126) 4%,rgb(96,41,182) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image='<?php echo esc_url( $img_url ); ?>'  bg_image_id='6335'  bg_image_xy='{x:0.5,y:0.62}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md='6'  pr_md=''  pb_md='6'  pl_md=''  pt_lg='8'  pr_lg='0'  pb_lg=''  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-md-6 pb-md-6 pt-lg-8 pe-0 ps-0 bg-custom-color d-flex container-fluid position-relative justify-content-center" style="background-color:rgba(0,0,0,0.77);background-image:url(<?php echo esc_url( $img_url ); ?>);background-blend-mode:overlay;background-size:cover;background-position:50% 62%"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"7","text_color":"white","pt_lg":"6","pr_lg":"5","pb_lg":"6","pl_lg":"5","border":"0","rounded_size":"3"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='7'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg='5'  pb_lg='6'  pl_lg='5'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='3'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 pt-6 pe-5 pb-6 ps-5 col-12 col-lg-7 border-0 rounded-3 text-white col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Invest in Your Future","html_tag":"h3","text_color":"white","text_color_custom":"#0c0d24","font_size":"fs-6","font_weight":"font-weight-bold","text_align_lg":"text-lg-center","ml_lg":"1"} -->
<h3 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 ms-1 text-white text-center font-weight-bold fs-6">Invest in Your Future</h3>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Future-Proof Your Business","html_tag":"h2","text_color":"white","text_color_custom":"#0c0d24","font_size":"display-3","font_weight":"font-weight-bold","text_align_lg":"text-lg-center"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-white text-center font-weight-bold display-3">Future-Proof Your Business</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Partner with us to develop a roadmap for sustainable success. Learn more about our services.","html_tag":"p","font_size":"fs-5","text_align_lg":"text-lg-center","mt":"3","mb":"4","mr_md":"0","ml_md":"0","mt_lg":"3","mb_lg":"4"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 mb-4 me-md-0 ms-md-0 mt-lg-3 mb-lg-4 text-center fs-5">Partner with us to develop a roadmap for sustainable success. Learn more about our services.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-container {"display_lg":"d-lg-flex","flex_justify_content_lg":"justify-content-lg-center"} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 d-flex container justify-content-center"><!-- wp:blockstrap/blockstrap-widget-button {"text":"Get a Quote","link_size":"large","font_size_custom":1.1,"font_weight":"font-weight-bold","mr_lg":"3","pt_lg":"3","pb_lg":"3","styleid":"block-4zcwjja02m","content":"\u003ca style=\u0022font-size:1.1rem;\u0022  class=\u0022btn btn-primary btn-lg me-3 pt-3 pb-3 fw-bold  block-4zcwjja02m \u0022\u003eGet a Quote\u003c/a\u003e "} -->
[bs_button type='home'  page_id=''  meta_key=''  post_id=''  custom_url=''  text='Get a Quote'  icon_class=''  icon_position=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover=''  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom='1.1'  font_weight='font-weight-bold'  font_case=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='3'  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg='3'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-4zcwjja02m' ]
<!-- /wp:blockstrap/blockstrap-widget-button -->

<!-- wp:blockstrap/blockstrap-widget-button {"text":"Contact Us","link_size":"large","font_size_custom":1.1,"font_weight":"font-weight-bold","pt_lg":"3","pb_lg":"3","styleid":"block-4zcwjja02m","content":"\u003ca style=\u0022font-size:1.1rem;\u0022  class=\u0022btn btn-primary btn-lg pt-3 pb-3 fw-bold  block-4zcwjja02m \u0022\u003eContact Us\u003c/a\u003e "} -->
[bs_button type='home'  page_id=''  meta_key=''  post_id=''  custom_url=''  text='Contact Us'  icon_class=''  icon_position=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover=''  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom='1.1'  font_weight='font-weight-bold'  font_case=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg='3'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-4zcwjja02m' ]
<!-- /wp:blockstrap/blockstrap-widget-button --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->