<?php
/**
 * Title: Classifieds - How it works
 * Slug: classifieds/how-it-works
 * Categories: call-to-action
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","pt":"2","pt_lg":"4","pb_lg":"5","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e"} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='2'  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg=''  pb_lg='5'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-2 pt-lg-4 pb-5 container"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"How it Works","html_tag":"p","text_color":"gray-dark","text_color_custom":"#0c0d24","font_size":"fs-5","text_align_lg":"text-lg-center","mb_lg":"2"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-2 text-gray-dark text-center fs-5">How it Works</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Explore the Simple Steps","html_tag":"h2","text_color_custom":"#0c0d24","font_size":"h1","font_weight":"font-weight-bold","text_align_lg":"text-lg-center","mb_lg":"5"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-5 text-center font-weight-bold h1">Explore the Simple Steps</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","row_cols_lg":"4","mt_lg":"4","mb_lg":"","flex_align_items_lg":"align-items-lg-center","flex_justify_content_lg":"justify-content-lg-center"} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md='2'  row_cols_lg='4'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='4'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mt-4 row-cols-1 row-cols-md-2 row-cols-lg-4 row align-items-center justify-content-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","bg":"custom-light-green","mb":"4","mb_lg":"","pt_lg":"5","pr_lg":"5","pb_lg":"5","pl_lg":"5","border":"0","position":"position-relative","display_lg":"d-lg-flex"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-light-green'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb='4'  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='5'  pb_lg='5'  pl_lg='5'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-4 pt-5 pe-5 pb-5 ps-5 border-0 bg-custom-light-green d-flex col position-relative"><!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-regular fa-address-card","title":"Register FREE","description":"Register your account with us completely FREE","icon_type":"iconbox-fill","iconbox_size":"large","icon_color":"white","icon_pb":"3","desc_color":"gray-dark","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100  \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon pb-3 text-white text-center \u0022  \u003e\u003ci class=\u0022fa-regular fa-address-card   iconbox border-0 fill rounded-circle bg-primary iconlarge \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ca class=\u0022blockstrap-iconbox-title-link stretched-link\u0022 \u003e\u003ch3 class=\u0022blockstrap-iconbox-title text-center h3   mb-0\u0022  \u003eRegister FREE\u003c/h3\u003e\u003c/a\u003e\u003cdiv class=\u0022blockstrap-iconbox-desc text-gray-dark text-center \u0022  \u003eRegister your account with us completely FREE\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-regular fa-address-card'  title='Register FREE'  title_tag='h3'  description='Register your account with us completely FREE'  type='home'  page_id=''  post_id=''  custom_url=''  icon_position=''  icon_type='iconbox-fill'  iconbox_size='large'  icon_size='h3'  icon_size_custom=''  icon_color='white'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg='text-lg-center'  icon_pb='3'  title_size='h3'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg='text-lg-center'  title_pb=''  desc_size=''  desc_size_custom=''  desc_font_line_height=''  desc_color='gray-dark'  desc_color_custom=''  desc_font_weight=''  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg='text-lg-center'  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","bg":"white","bg_color":"#efefef","mb":"4","mb_lg":"","pt_lg":"5","pr_lg":"5","pb_lg":"5","pl_lg":"5","border":"0","display_lg":"d-lg-flex"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='white'  bg_color='#efefef'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb='4'  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='5'  pb_lg='5'  pl_lg='5'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-4 pt-5 pe-5 pb-5 ps-5 border-0 bg-white d-flex col"><!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-regular fa-paper-plane","title":"Submit Ad","description":"Submit your business, services, products or discounts","icon_type":"iconbox-fill","iconbox_size":"large","icon_color":"white","icon_pb":"4","desc_color":"gray-dark","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100  \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon pb-4 text-white text-center \u0022  \u003e\u003ci class=\u0022fa-regular fa-paper-plane   iconbox border-0 fill rounded-circle bg-primary iconlarge \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ca class=\u0022blockstrap-iconbox-title-link stretched-link\u0022 \u003e\u003ch3 class=\u0022blockstrap-iconbox-title text-center h3   mb-0\u0022  \u003eSubmit Ad\u003c/h3\u003e\u003c/a\u003e\u003cdiv class=\u0022blockstrap-iconbox-desc text-gray-dark text-center \u0022  \u003eSubmit your business, services, products or discounts\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-regular fa-paper-plane'  title='Submit Ad'  title_tag='h3'  description='Submit your business, services, products or discounts'  type='home'  page_id=''  post_id=''  custom_url=''  icon_position=''  icon_type='iconbox-fill'  iconbox_size='large'  icon_size='h3'  icon_size_custom=''  icon_color='white'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg='text-lg-center'  icon_pb='4'  title_size='h3'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg='text-lg-center'  title_pb=''  desc_size=''  desc_size_custom=''  desc_font_line_height=''  desc_color='gray-dark'  desc_color_custom=''  desc_font_weight=''  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg='text-lg-center'  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","bg":"custom-light-green","mb":"4","mb_lg":"","pt_lg":"5","pr_lg":"5","pb_lg":"5","pl_lg":"5","border":"0","display_lg":"d-lg-flex"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-light-green'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb='4'  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='5'  pb_lg='5'  pl_lg='5'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-4 pt-5 pe-5 pb-5 ps-5 border-0 bg-custom-light-green d-flex col"><!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-regular fa-sun","title":"Get Exposure","description":"Start selling faster or get more exposure with Lisfinity","icon_type":"iconbox-fill","iconbox_size":"large","icon_color":"white","icon_pb":"4","desc_color":"gray-dark","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100  \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon pb-4 text-white text-center \u0022  \u003e\u003ci class=\u0022fa-regular fa-sun   iconbox border-0 fill rounded-circle bg-primary iconlarge \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ca class=\u0022blockstrap-iconbox-title-link stretched-link\u0022 \u003e\u003ch3 class=\u0022blockstrap-iconbox-title text-center h3   mb-0\u0022  \u003eGet Exposure\u003c/h3\u003e\u003c/a\u003e\u003cdiv class=\u0022blockstrap-iconbox-desc text-gray-dark text-center \u0022  \u003eStart selling faster or get more exposure with Lisfinity\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-regular fa-sun'  title='Get Exposure'  title_tag='h3'  description='Start selling faster or get more exposure with Lisfinity'  type='home'  page_id=''  post_id=''  custom_url=''  icon_position=''  icon_type='iconbox-fill'  iconbox_size='large'  icon_size='h3'  icon_size_custom=''  icon_color='white'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg='text-lg-center'  icon_pb='4'  title_size='h3'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg='text-lg-center'  title_pb=''  desc_size=''  desc_size_custom=''  desc_font_line_height=''  desc_color='gray-dark'  desc_color_custom=''  desc_font_weight=''  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg='text-lg-center'  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","text_align_lg":"text-lg-center","mt_lg":"2","mb_lg":""} -->
[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='2'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mt-2 text-center row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":""} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined col"><!-- wp:blockstrap/blockstrap-widget-button {"type":"custom","custom_url":"#","text":"Get Started","link_type":"btn-round","link_size":"large","font_size_custom":1.1,"font_weight":"font-weight-bold","font_case":"text-capitalize","mt_lg":"3","pt_lg":"3","pb_lg":"3","styleid":"block-uceu972akzk","content":"\u003ca style=\u0022font-size:1.1rem;\u0022  class=\u0022btn btn-round btn-primary btn-lg mt-3 pt-3 pb-3 fw-bold  text-capitalize  block-uceu972akzk \u0022\u003eGet Started\u003c/a\u003e "} -->
[bs_button type='custom'  page_id=''  meta_key=''  post_id=''  custom_url='#'  text='Get Started'  icon_class=''  icon_position=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn-round'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover=''  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom='1.1'  font_weight='font-weight-bold'  font_case='text-capitalize'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='3'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg='3'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-uceu972akzk' ]
<!-- /wp:blockstrap/blockstrap-widget-button --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->