<?php
/**
 * Title: Classifieds - Listings Carousel
 * Slug: classified-ads-listings/listings-carousel
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg_color":"#fffbf2","bg_gradient":"linear-gradient(90deg,rgba(0,0,0,0.73) 4%,rgba(121,33,12,0.86) 100%)","bg_image_xy":{"x":0.75,"y":0.99},"text_color":"white","mt_lg":"n7","mb_lg":"","pt":"6","pb":"0","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#fffbf2'  bg_gradient='linear-gradient(90deg,rgba(0,0,0,0.73) 4%,rgba(121,33,12,0.86) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='n7'  mr_lg=''  mb_lg=''  ml_lg=''  pt='6'  pr=''  pb='0'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mt-n7 pt-6 pb-0 pt-lg-0 pe-0 pb-lg-0 ps-0 bg-image-fixed text-white container-fluid"><!-- wp:geodirectory/geodir-widget-listings {"show_advanced":true,"category":["0"],"post_limit":8,"add_location_filter":false,"sort_by":"latest","layout":"4","view_all_link":false,"template_type":"template_part","tmpl_part":"gd-archive-item","with_carousel":"1","with_controls":"1","center_slide":"1","mb":"","content": "","sd_shortcode":"[gd_listings title=''  widget_title_tag=''  widget_title_size_class=''  widget_title_align_class=''  widget_title_color_class=''  widget_title_border_class=''  widget_title_border_color_class=''  widget_title_mt_class=''  widget_title_mr_class=''  widget_title_mb_class=''  widget_title_ml_class=''  widget_title_pt_class=''  widget_title_pr_class=''  widget_title_pb_class=''  widget_title_pl_class=''  hide_if_empty='false'  post_type='gd_place'  category='0'  related_to=''  tags=''  post_author=''  post_limit='8'  post_ids=''  add_location_filter='false'  nearby_gps='false'  show_featured_only='false'  show_special_only='false'  with_pics_only='false'  with_videos_only='false'  show_favorites_only='false'  favorites_by_user=''  use_viewing_post_type='false'  use_viewing_term='false'  sort_by='latest'  title_tag='h3'  layout='4'  view_all_link='false'  with_pagination='false'  top_pagination='false'  bottom_pagination='true'  pagination_info=''  template_type='template_part'  tmpl_page=''  tmpl_part='gd-archive-item'  row_gap=''  column_gap=''  card_border=''  card_shadow=''  with_carousel='1'  with_indicators=''  indicators_mb=''  with_controls='1'  slide_interval='5'  slide_ride=''  center_slide='1'  bg=''  mt=''  mr=''  mb=''  ml=''  pt=''  pr=''  pb=''  pl=''  border=''  rounded=''  rounded_size=''  shadow=''  css_class='' ]"} -->
    <div class="wp-block-geodirectory-geodir-widget-listings"></div>
    <!-- /wp:geodirectory/geodir-widget-listings --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->