<?php
/**
 * Title: Consulting - How it works
 * Slug: consulting/take-action
 * Categories: call-to-action
 * Viewport Width: 1280
 */

 $img_url = esc_url( get_theme_file_uri( 'assets/images/demo/business-man-3.jpg' ) ); /* <?php echo esc_url( $img_url ); ?> */
 $img_url2 = esc_url( get_theme_file_uri( 'assets/images/demo/business-man-2.jpg' ) ); /* <?php echo esc_url( $img_url2 ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e"} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","mb_lg":"","pt":"3","pr":"3","pl":"3","pt_lg":"0","pb_lg":"5","flex_align_items_lg":"align-items-lg-center"} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='3'  pr='3'  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg=''  pb_lg='5'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-3 pe-3 ps-3 pt-lg-0 pb-5 row-cols-1 row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_md":"12","col_lg":"5","mb_lg":"","pr":"0","pl":"0","pt_md":"0","pr_md":"0","pt_lg":"5","pr_lg":"6","pb_lg":"5"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md='12'  col_lg='5'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='0'  pb=''  pl='0'  pt_md='0'  pr_md='0'  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='6'  pb_lg='5'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pe-0 ps-0 pt-md-0 pe-md-0 pt-lg-5 pe-lg-6 pb-5 col-md-12 col-lg-5 col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Take Action","html_tag":"h3","text_color":"primary","text_color_custom":"#0c0d24","font_size":"fs-6","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","ml_lg":"1"} -->
<h3 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 ms-1 text-primary text-start font-weight-bold fs-6">Take Action</h3>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Drive Measurable Results","html_tag":"h2","text_color_custom":"#0c0d24","font_size":"display-3","font_weight":"font-weight-bold","text_align_lg":"text-lg-start"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-start font-weight-bold display-3">Drive Measurable Results</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Let's collaborate to achieve your business goals. Schedule a free consultation today.","html_tag":"p","font_size":"fs-5","text_align_lg":"text-lg-start","mt":"3","mb":"4","mr_md":"0","ml_md":"0","mt_lg":"3","mb_lg":"4"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 mb-4 me-md-0 ms-md-0 mt-lg-3 mb-lg-4 text-start fs-5">Let's collaborate to achieve your business goals. Schedule a free consultation today.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-button {"text":"Get Quote Now","link_size":"large","font_weight":"font-weight-bold","mt_lg":"2","styleid":"block-4zcwjja02m","content":"\u003ca   class=\u0022btn btn-primary btn-lg mt-2 fw-bold  block-4zcwjja02m \u0022\u003eGet Quote Now\u003c/a\u003e "} -->
[bs_button type='home'  page_id=''  meta_key=''  post_id=''  custom_url=''  text='Get Quote Now'  icon_class=''  icon_position=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover=''  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom=''  font_weight='font-weight-bold'  font_case=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='2'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-4zcwjja02m' ]
<!-- /wp:blockstrap/blockstrap-widget-button --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"4","col_md":"4","col_lg":"3","mb_lg":"","pt":"0","pr":"0","pb":"0","pl":"0","pt_md":"0","pr_md":"0","pb_md":"0","pl_md":"0","border":"0","rounded":"rounded","display_lg":"d-lg-flex"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='4'  col_md='4'  col_lg='3'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='0'  pr='0'  pb='0'  pl='0'  pt_md='0'  pr_md='0'  pb_md='0'  pl_md='0'  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-0 pe-0 pb-0 ps-0 pt-md-0 pe-md-0 pb-md-0 ps-md-0 col-4 col-md-4 col-lg-3 border-0 d-flex col rounded"><!-- wp:blockstrap/blockstrap-widget-image {"img_image":"<?php echo esc_url( $img_url2 ); ?>","img_image_id":6314,"img_rounded_size":"4","img_shadow":"shadow-lg","mb_lg":"","content":"\u003cfigure class=\u0022  embed-has-actionoverflow-hidden mb-3 \u0022 style=\u0022 \u0022\u003e\u003cimg width=\u0022960\u0022 height=\u00221440\u0022 src=\u0022<?php echo esc_url( $img_url2 ); ?>\u0022 class=\u0022mw-100 w-100 rounded-4 shadow-lg embed-item-cover-xy \u0022 alt=\u0022\u0022 decoding=\u0022async\u0022 fetchpriority=\u0022high\u0022 srcset=\u0022<?php echo esc_url( $img_url2 ); ?> 960w, http://consulting.local/wp-content/uploads/2024/04/business-man-2-200x300.jpeg 200w, http://consulting.local/wp-content/uploads/2024/04/business-man-2-683x1024.jpeg 683w, http://consulting.local/wp-content/uploads/2024/04/business-man-2-768x1152.jpeg 768w\u0022 sizes=\u0022(max-width: 960px) 100vw, 960px\u0022 /\u003e\u003c/figure\u003e"} -->
[bs_image img_src='upload'  img_image='<?php echo esc_url( $img_url2 ); ?>'  img_image_id='6314'  img_size=''  img_url=''  fallback_img_src=''  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect=''  img_cover=''  img_border=''  img_rounded=''  img_rounded_size='4'  img_shadow='shadow-lg'  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-image --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"8","col_md":"8","col_lg":"4","mb_lg":"","pr_md":"0","pl_md":"4","border":"0","rounded":"rounded","display_lg":"d-lg-flex"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='8'  col_md='8'  col_lg='4'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md='0'  pb_md=''  pl_md='4'  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pe-md-0 ps-md-4 col-8 col-md-8 col-lg-4 border-0 d-flex col rounded"><!-- wp:blockstrap/blockstrap-widget-image {"img_image":"<?php echo esc_url( $img_url ); ?>","img_image_id":6317,"fallback_img_src":"default","img_rounded_size":"4","img_shadow":"shadow-lg","mr":"0","mb":"0","ml":"0","mr_md":"0","mb_md":"0","ml_md":"0","mb_lg":"","ml_lg":"n5","content":"\u003cfigure class=\u0022  embed-has-actionoverflow-hidden me-0 mb-0 ms-0 me-md-0 mb-md-0 ms-md-0 mb-lg-3 ms-lg-n5 \u0022 style=\u0022 \u0022\u003e\u003cimg width=\u0022960\u0022 height=\u0022640\u0022 src=\u0022<?php echo esc_url( $img_url ); ?>\u0022 class=\u0022mw-100 w-100 rounded-4 shadow-lg embed-item-cover-xy \u0022 alt=\u0022\u0022 decoding=\u0022async\u0022 fetchpriority=\u0022high\u0022 srcset=\u0022<?php echo esc_url( $img_url ); ?> 960w, http://consulting.local/wp-content/uploads/2024/04/business-man-3-300x200.jpeg 300w, http://consulting.local/wp-content/uploads/2024/04/business-man-3-768x512.jpeg 768w\u0022 sizes=\u0022(max-width: 960px) 100vw, 960px\u0022 /\u003e\u003c/figure\u003e"} -->
[bs_image img_src='upload'  img_image='<?php echo esc_url( $img_url ); ?>'  img_image_id='6317'  img_size=''  img_url=''  fallback_img_src='default'  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect=''  img_cover=''  img_border=''  img_rounded=''  img_rounded_size='4'  img_shadow='shadow-lg'  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr='0'  mb='0'  ml='0'  mt_md=''  mr_md='0'  mb_md='0'  ml_md='0'  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='n5'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-image --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->