<?php
/**
 * Title: Consulting: 4-column cards (Latest articles)
 * Slug: consulting/three-col-posts
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"bg_color":"rgba(0,0,0,0.85)","bg_gradient":"radial-gradient(rgb(5,63,40) 0%,rgba(11,23,18,0.93) 100%)","bg_image_fixed":true,"bg_image_xy":{"x":0.75,"y":0.99},"text_color":"white","mb_lg":"","pt":"3","pt_lg":"7","pr_lg":"3","pb_lg":"6","pl_lg":"3","position":"position-relative","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e"} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(0,0,0,0.85)'  bg_gradient='radial-gradient(rgb(5,63,40) 0%,rgba(11,23,18,0.93) 100%)'  bg_image_fixed='true'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:0.75,y:0.99}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='3'  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='7'  pr_lg='3'  pb_lg='6'  pl_lg='3'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-3 pt-lg-7 pe-3 pb-6 ps-3 text-white container position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","text_align_lg":"text-lg-center","mb_lg":"","pb":"0","pb_lg":"4"} -->
[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb='0'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='4'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pb-0 pb-lg-4 text-center row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":""} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Latest Insights","html_tag":"h3","text_color":"primary","text_color_custom":"#0c0d24","font_size":"fs-6","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","ml_lg":"1"} -->
<h3 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 ms-1 text-primary text-start font-weight-bold fs-6">Latest Insights</h3>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Stay Ahead of the Curve","html_tag":"h2","text_color_custom":"#0c0d24","font_size":"display-3","font_weight":"font-weight-bold","text_align_lg":"text-lg-start"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-start font-weight-bold display-3">Stay Ahead of the Curve</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:query {"queryId":1,"query":{"pages":"","offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","sticky":"","exclude":[],"perPage":"6","inherit":false,"parents":[],"taxQuery":null},"layout":{"type":"default"}} -->
<div class="wp-block-query"><!-- wp:post-template {"layout":{"type":"grid","columnCount":3}} -->
<!-- wp:blockstrap/blockstrap-widget-container {"container":"card","h100":"h-100","bg":"white","mt_lg":"0","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","border":"0","rounded_size":"0","overflow":"overflow-hidden"} -->
[bs_container container='card'  h100='h-100'  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='white'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='0'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mt-0 pt-0 pe-0 pb-0 ps-0 border-0 rounded-0 bg-white card h-100 overflow-hidden"><!-- wp:cover {"useFeaturedImage":true,"hasParallax":true,"dimRatio":50,"isUserOverlayColor":true,"minHeight":50,"minHeightUnit":"vh","customGradient":"linear-gradient(183deg,rgba(255,255,255,0.04) 0%,rgb(19,17,17) 67%,rgb(0,0,0) 100%)","contentPosition":"bottom center","style":{"spacing":{"blockGap":"0","padding":{"right":"var:preset|spacing|60","left":"var:preset|spacing|60"}},"elements":{"link":{"color":{"text":"var:preset|color|white"}},"heading":{"color":{"text":"var:preset|color|white"}}},"border":{"radius":"0.75rem"}},"textColor":"white","layout":{"type":"default"}} -->
<div class="wp-block-cover has-parallax has-custom-content-position is-position-bottom-center has-white-color has-text-color has-link-color" style="border-radius:0.75rem;padding-right:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--60);min-height:50vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim has-background-gradient" style="background:linear-gradient(183deg,rgba(255,255,255,0.04) 0%,rgb(19,17,17) 67%,rgb(0,0,0) 100%)"></span><div class="wp-block-cover__inner-container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"","text_color":"white","mb_lg":""} -->
[bs_container container=''  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined text-white"><!-- wp:post-date {"textAlign":"left","style":{"typography":{"fontSize":"0.9rem","fontStyle":"normal","fontWeight":"600"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white"} /-->

<!-- wp:post-title {"level":3,"isLink":true,"style":{"elements":{"link":{"color":{"text":"var:preset|color|white"},":hover":{"color":{"text":"var:preset|color|white"}}}},"typography":{"fontStyle":"normal","fontWeight":"700"}},"textColor":"white","fontSize":"large"} /--></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div></div>
<!-- /wp:cover --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->
<!-- /wp:post-template -->

<!-- wp:template-part {"slug":"no-results","theme":"consulting"} /--></div>
<!-- /wp:query --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->