<?php
/**
 * Title: Consulting - How it works
 * Slug: consulting/trusted-expertise
 * Categories: call-to-action
 * Viewport Width: 1280
 */

 $img_url = esc_url( get_theme_file_uri( 'assets/images/demo/business-man-4.jpeg' ) ); /* <?php echo esc_url( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"#fbfbfb","mb_lg":"","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='#fbfbfb'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined bg-custom-color container-fluid" style="background-color:#fbfbfb"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_lg":"2","mb_lg":"","flex_align_items_lg":"align-items-lg-center"} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md=''  row_cols_lg='2'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row-cols-1 row-cols-lg-2 row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"8","col_lg":"6","mb_lg":"","pr":"3","pr_md":"6","pl_md":"6","pt_lg":"5","pr_lg":"6","pb_lg":"5","pl_lg":"6"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='8'  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='3'  pb=''  pl=''  pt_md=''  pr_md='6'  pb_md=''  pl_md='6'  pt_lg='5'  pr_lg='6'  pb_lg='5'  pl_lg='6'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pe-3 pe-md-6 ps-md-6 pt-5 pe-lg-6 pb-5 ps-lg-6 col-12 col-md-8 col-lg-6 col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Trusted Expertise","html_tag":"h3","text_color":"primary","text_color_custom":"#0c0d24","font_size":"fs-6","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","ml_lg":"1"} -->
<h3 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 ms-1 text-primary text-start font-weight-bold fs-6">Trusted Expertise</h3>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Expert Guidance Awaits","html_tag":"h2","text_color_custom":"#0c0d24","font_size":"display-3","font_weight":"font-weight-bold","text_align_lg":"text-lg-start"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-start font-weight-bold display-3">Expert Guidance Awaits</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-accordion {"collapse":"close","anchor":"your-success","mb_lg":"4"} -->
[bs_accordion style=''  collapse='close'  anchor='your-success'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='4'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-accordion accordion mb-4" id="your-success"><!-- wp:blockstrap/blockstrap-widget-accordion-item {"text":"Deep Expertise","anchor":"deep-expertise","parent_anchor":"your-success","state":"closed","shadow":"shadow-sm"} -->
[bs_accordion_item text='Deep Expertise'  anchor='deep-expertise'  parent_anchor='your-success'  state='closed'  bg=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow='shadow-sm'  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class='' ]<div class="accordion-item" id="heading-deep-expertise"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-deep-expertise" aria-expanded="false" aria-controls="collapse-deep-expertise">Deep Expertise</button></h2><div class="accordion-collapse collapse" x="" id="collapse-deep-expertise" aria-labelledby="heading-deep-expertise" data-bs-parent="#your-success"><div class="wp-block-blockstrap-blockstrap-widget-accordion-item accordion-body shadow-sm"><!-- wp:paragraph {"placeholder":"Add your blocks here"} -->
<p>Proven Track Record: Our consultants have a history of success, delivering measurable results across diverse industries.</p>
<!-- /wp:paragraph --></div></div></div>[/bs_accordion_item]
<!-- /wp:blockstrap/blockstrap-widget-accordion-item -->

<!-- wp:blockstrap/blockstrap-widget-accordion-item {"text":"Strategic Thinking","anchor":"strategic-thinking","parent_anchor":"your-success","state":"closed","shadow":"shadow-sm"} -->
[bs_accordion_item text='Strategic Thinking'  anchor='strategic-thinking'  parent_anchor='your-success'  state='closed'  bg=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow='shadow-sm'  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class='' ]<div class="accordion-item" id="heading-strategic-thinking"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-strategic-thinking" aria-expanded="false" aria-controls="collapse-strategic-thinking">Strategic Thinking</button></h2><div class="accordion-collapse collapse" x="" id="collapse-strategic-thinking" aria-labelledby="heading-strategic-thinking" data-bs-parent="#your-success"><div class="wp-block-blockstrap-blockstrap-widget-accordion-item accordion-body shadow-sm"><!-- wp:paragraph {"placeholder":"Add your blocks here"} -->
<p>Insightful Solutions: We go beyond the surface, crafting customized strategies that address your unique challenges and goals.</p>
<!-- /wp:paragraph --></div></div></div>[/bs_accordion_item]
<!-- /wp:blockstrap/blockstrap-widget-accordion-item -->

<!-- wp:blockstrap/blockstrap-widget-accordion-item {"text":"Collaborative Approach","anchor":"collaborative-approach","parent_anchor":"your-success","state":"closed","shadow":"shadow-sm"} -->
[bs_accordion_item text='Collaborative Approach'  anchor='collaborative-approach'  parent_anchor='your-success'  state='closed'  bg=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow='shadow-sm'  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class='' ]<div class="accordion-item" id="heading-collaborative-approach"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-collaborative-approach" aria-expanded="false" aria-controls="collapse-collaborative-approach">Collaborative Approach</button></h2><div class="accordion-collapse collapse" x="" id="collapse-collaborative-approach" aria-labelledby="heading-collaborative-approach" data-bs-parent="#your-success"><div class="wp-block-blockstrap-blockstrap-widget-accordion-item accordion-body shadow-sm"><!-- wp:paragraph {"placeholder":"Add your blocks here"} -->
<p>Partnership for Growth: We work alongside you, fostering open communication and building trust for a successful journey.</p>
<!-- /wp:paragraph --></div></div></div>[/bs_accordion_item]
<!-- /wp:blockstrap/blockstrap-widget-accordion-item --></div>[/bs_accordion]
<!-- /wp:blockstrap/blockstrap-widget-accordion -->

<!-- wp:blockstrap/blockstrap-widget-button {"text":"Get Quote Now","link_size":"large","font_weight":"font-weight-bold","mt_lg":"2","styleid":"block-4zcwjja02m","content":"\u003ca   class=\u0022btn btn-primary btn-lg mt-2 fw-bold  block-4zcwjja02m \u0022\u003eGet Quote Now\u003c/a\u003e "} -->
[bs_button type='home'  page_id=''  meta_key=''  post_id=''  custom_url=''  text='Get Quote Now'  icon_class=''  icon_position=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover=''  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom=''  font_weight='font-weight-bold'  font_case=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='2'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-4zcwjja02m' ]
<!-- /wp:blockstrap/blockstrap-widget-button --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"4","col_lg":"6","mb_lg":"","pr_lg":"0","pl_lg":"0","border":"0","display":"d-none","display_md":"d-md-block"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='4'  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='0'  pb_lg=''  pl_lg='0'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display='d-none'  display_md='d-md-block'  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pe-0 ps-0 col-12 col-md-4 col-lg-6 border-0 d-none d-md-block col"><!-- wp:cover {"url":"<?php echo esc_url( $img_url ); ?>","id":6121,"hasParallax":true,"dimRatio":0,"customOverlayColor":"#a9a7a4","minHeight":800,"minHeightUnit":"px","isDark":false,"layout":{"type":"default"}} -->
<div class="wp-block-cover is-light has-parallax" style="min-height:800px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim" style="background-color:#a9a7a4"></span><div class="wp-block-cover__image-background wp-image-6121 has-parallax" style="background-position:50% 50%;background-image:url(<?php echo esc_url( $img_url ); ?>)"></div><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->