<?php
/**
 * Title: Consulting - How it works
 * Slug: consulting/unleash-potential
 * Categories: call-to-action
 * Viewport Width: 1280
 */

 $img_url = esc_url( get_theme_file_uri( 'assets/images/demo/business-man.jpeg' ) ); /* <?php echo esc_url( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e"} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","mb_lg":"","pt":"3","pr":"3","pl":"3","pt_lg":"6","pb_lg":"2","flex_align_items_lg":"align-items-lg-center"} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='3'  pr='3'  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg=''  pb_lg='2'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-3 pe-3 ps-3 pt-lg-6 pb-2 row-cols-1 row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_md":"12","col_lg":"6","mb_lg":"","pt":"0","pr":"0","pb":"0","pl":"0","pt_md":"0","pr_md":"0","pb_md":"0","pl_md":"0","pr_lg":"0","pb_lg":"4","border":"0","rounded":"rounded","flex_order":"order-2","flex_order_lg":"order-lg-1"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md='12'  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='0'  pr='0'  pb='0'  pl='0'  pt_md='0'  pr_md='0'  pb_md='0'  pl_md='0'  pt_lg=''  pr_lg='0'  pb_lg='4'  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order='order-2'  flex_order_md=''  flex_order_lg='order-lg-1'  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-0 pe-0 pb-0 ps-0 pt-md-0 pe-md-0 pb-md-0 ps-md-0 pe-lg-0 pb-lg-4 col-md-12 col-lg-6 border-0 col rounded order-2 order-lg-1"><!-- wp:blockstrap/blockstrap-widget-image {"img_image":"<?php echo esc_url( $img_url ); ?>","img_image_id":6121,"fallback_img_src":"default","img_cover":"n","img_rounded":"rounded","img_shadow":"shadow-lg","mb_lg":"0","content":"\u003cfigure class=\u0022  embed-has-actionoverflow-hidden mb-0 \u0022 style=\u0022 \u0022\u003e\u003cimg width=\u0022960\u0022 height=\u0022640\u0022 src=\u0022http://consulting.local/wp-content/uploads/2024/04/business-man.jpeg\u0022 class=\u0022mw-100 w-100 rounded shadow-lg embed-item-contain \u0022 alt=\u0022\u0022 decoding=\u0022async\u0022 fetchpriority=\u0022high\u0022 srcset=\u0022http://consulting.local/wp-content/uploads/2024/04/business-man.jpeg 960w, http://consulting.local/wp-content/uploads/2024/04/business-man-300x200.jpeg 300w, http://consulting.local/wp-content/uploads/2024/04/business-man-768x512.jpeg 768w\u0022 sizes=\u0022(max-width: 960px) 100vw, 960px\u0022 /\u003e\u003c/figure\u003e"} -->
[bs_image img_src='upload'  img_image='<?php echo esc_url( $img_url ); ?>'  img_image_id='6121'  img_size=''  img_url=''  fallback_img_src='default'  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect=''  img_cover='n'  img_border=''  img_rounded='rounded'  img_rounded_size=''  img_shadow='shadow-lg'  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-image --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_md":"12","col_lg":"6","mb_lg":"","pr":"0","pl":"0","pt_md":"0","pr_md":"0","pt_lg":"5","pb_lg":"5","pl_lg":"6","flex_order":"order-1","flex_order_lg":"order-lg-2"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md='12'  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='0'  pb=''  pl='0'  pt_md='0'  pr_md='0'  pb_md=''  pl_md=''  pt_lg='5'  pr_lg=''  pb_lg='5'  pl_lg='6'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order='order-1'  flex_order_md=''  flex_order_lg='order-lg-2'  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pe-0 ps-0 pt-md-0 pe-md-0 pt-lg-5 pb-5 ps-lg-6 col-md-12 col-lg-6 col order-1 order-lg-2"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Unleash Your Potential","html_tag":"h3","text_color":"primary","text_color_custom":"#0c0d24","font_size":"fs-6","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","ml_lg":"1"} -->
<h3 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 ms-1 text-primary text-start font-weight-bold fs-6">Unleash Your Potential</h3>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Discover Growth Opportunities","html_tag":"h2","text_color_custom":"#0c0d24","font_size":"display-3","font_weight":"font-weight-bold","text_align_lg":"text-lg-start"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-start font-weight-bold display-3">Discover Growth Opportunities</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Explore our tailored solutions and unlock your full potential. Browse our services.","html_tag":"p","font_size":"fs-5","text_align_lg":"text-lg-start","mt":"3","mb":"4","mr_md":"0","ml_md":"0","mt_lg":"3","mb_lg":"4"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 mb-4 me-md-0 ms-md-0 mt-lg-3 mb-lg-4 text-start fs-5">Explore our tailored solutions and unlock your full potential. Browse our services.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-button {"text":"Get Quote Now","link_size":"large","font_weight":"font-weight-bold","mt_lg":"2","styleid":"block-4zcwjja02m","content":"\u003ca   class=\u0022btn btn-primary btn-lg mt-2 fw-bold  block-4zcwjja02m \u0022\u003eGet Quote Now\u003c/a\u003e "} -->
[bs_button type='home'  page_id=''  meta_key=''  post_id=''  custom_url=''  text='Get Quote Now'  icon_class=''  icon_position=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover=''  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom=''  font_weight='font-weight-bold'  font_case=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='2'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-4zcwjja02m' ]
<!-- /wp:blockstrap/blockstrap-widget-button --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->